session: prepare now prepares on all nodes
scylladb/scylla-go-driver pull request #266
Opened 2022-08-01 16:56 UTC by Kulezi

Fixes #249

2022-08-02 10:03 UTC, piodul requested changes
While I think it is a worthwhile change, it shouldn't declare that it fixes #249. AFAIK #249 points out that the protocol specification technically allows different nodes to use different IDs for the same prepared statement. This PR still works under this assumption, it's just that prepared statements are prepared up-front on all nodes.

IMO it's fine to fix this later. All other drivers that I know, including the Java driver, currently seem to work under that assumption, so I doubt the current behavior will be changed soon by either Cassandra or Scylla.

2022-08-03 10:02 UTC, Kulezi commented on transport/cluster.go
> +		}
Creating the test i encountered a missing keyspace error that "" was not found in system_schema.keyspaces, currently the driver always assumes it's querying the default session keyspace which needs to be changed with #257, right now the driver doesn't save info about keyspace from prepared results, hence i needed this workaround.

I moved it to another commit.

2022-08-03 10:05 UTC, Kulezi commented
Applied changes suggested by @piodul, also removed leaking goroutines from TLS integration test caused by unclosed session.

2022-08-03 11:17 UTC, piodul approved these changes

2022-08-05 10:42 UTC, merged